require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

spec("user.coloscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.lspconfig")
spec("user.nonels")
spec("user.telescope")
spec("user.nvimtree")
spec("user.lualine")
spec("user.whichkey")
spec("user.copilot")
spec("user.cmp")
spec("user.autopairs")
spec("user.comment")
spec("user.gitsigns")
spec("user.neogit")
spec("user.indentline")
spec("user.alpha")
spec("user.project")
spec("user.breadcrumbs")
spec("user.navic")
spec("user.dap")
spec("user.dapui")
spec("user.dressing")
spec("user.harpoon")
spec("user.todo")
spec("user.scrolloff")



require("user.lazy")
