vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.o.clipboard = "unnamedplus"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true
vim.o.hlsearch = false
vim.wo.signcolumn = "yes"
vim.o.updatetime = 250
vim.o.timeoutlen = 300
vim.o.completeopt = "menuone,noselect"
vim.o.termguicolors = true
vim.o.wrap = false
vim.opt.cursorline = true
vim.opt.colorcolumn = "90"
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.history = 1000
vim.opt.showmode = false
vim.opt.conceallevel = 3
vim.opt.spell = true
vim.opt.spelllang = { "en", "it" }
vim.opt.cmdheight = 0
vim.opt.foldcolumn = "1"
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
vim.opt.foldenable = true

-- options recommended by nvim-tree
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
-- recommended by bufferline and nvim-tree (and pretty much anyone not using just the 16 terminal colors)
vim.o.termguicolors = true
